# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3fa0517208964cdb5679fcec12a263dd36727c9bf9fcf0207fd6856a536e8ff529b7cf5507a8ae5eafdace171aeb5987a2dc6e8e7dc917dccf42662022771c80

test:
  secret_key_base: 8afe5dc36b5dbbf82393d89cee93292e0691571d615b33d2022981fd0b7b467b55d160d1b9a0edce734a77bf089c5117e692c88e7f140a99a089b67e30c67de8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
